### ISSUE TITLE
How to set load balance policy on the cluster?

### ISSUE THREAD

**Issue by MarkFuini** [datanucleus/datanucleus-cassandra#35]
## Bug Report, attach a testcase using [problem guide](http://www.datanucleus.org/documentation/problem_reporting.html) and state what version the problem occurs in. Any "Bug" without a testcase will be CLOSED.

Looks like the cluster builder is created without ability to change any parameters is there any workaround for this?

**Comment by andyjefferson** [comment]
Questions should be posted on the provided support forums at Gitter or groups.io. 
A question is not an issue. Thx

**Comment by andyjefferson** [comment]
Since there has never been a contrib to provide this, it clearly wasn't as "urgent" as advised at the time ...
